export const SEARCHITEMS_REQUEST ="SEARCHITEMS_REQUEST"
export const SEARCHITEMS_SUCCESS="SEARCHITEMS_SUCCESS"
export const SEARCHITEMS_FAILURE="SEARCHITEMS_FAILURE"

export const FOODITEMS_REQUEST="FOODITEMS_REQUEST"
export const FOODITEMS_SUCCESS="FOODITEMS_SUCCESS"
export const FOODITEMS_FAILURE="FOODITEMS_FAILURE"